ITEAProject/ITEAProject/Models/Branch.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace ITEAProject.Models
{
    //Сущность филиала сети приютов
    public class Branch
    {
        public int Id { get; set; }
        [Required]
        public string Phone { get; set; }
        [Required]
        [MinLength(3)]
        public string Address { get; set; }
        public List<Pet> Pets { get; set; }
    }
}

ITEAProject/ITEAProject/Controllers/BranchController.cs
using ITEAProject.Models;
using ITEAProject.Models.ModelRepositories;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ITEAProject.Controllers
{
    public class BranchController : Controller
    {
        private IBranchRepository _branchRepository;

        public BranchController(IBranchRepository branchRepository)
        {
            _branchRepository = branchRepository;
        }
        public IActionResult Index()
        {
            return View(_branchRepository.AllBranches());
        }

        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Create(Branch branch)
        {
            if (ModelState.IsValid)
            {
                _branchRepository.NewBranch(branch);
                return Redirect("~/Branch/Index");
            }
           // return View();
            return View("Create");
        }

        [HttpGet]
        public IActionResult Update(int Id)
        {
            Branch branch = _branchRepository.AllBranches().Where(br=> br.Id==Id).First();
            return View(branch);
        }

        [HttpPost]
        public IActionResult Update(Branch branch)
        {
            if (ModelState.IsValid)
            {
                _branchRepository.EditBranch(branch);
                return Redirect("~/Branch/Index");
            }
            return View(branch);
        }

        public IActionResult Delete(int id)
        {
            _branchRepository.DeleteBranch(id);
            return Redirect("~/Branch/Index");
        }
    }
}

ITEAProject/ITEAProject/Controllers/PetController.cs
using ITEAProject.Models;
using ITEAProject.Models.ModelRepositories;
using ITEAProject.ViewModels;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ITEAProject.Controllers
{
    public class PetController : Controller
    {
        private IPetRepository _petRepository;
        private IBranchRepository _branchRepository;
        private IBreedRepository _breedRepository;
        private IOwnerRepository _ownerRepository;

        public PetController(IPetRepository petRepository, IBreedRepository breedRepository, 
                             IBranchRepository branchRepository, IOwnerRepository ownerRepository)
        {
            _petRepository = petRepository;
            _breedRepository = breedRepository;
            _branchRepository = branchRepository;
            _ownerRepository = ownerRepository;
        }
        public IActionResult Index(int? Id)
        {
            IEnumerable<PetIndexViewModel> pets;
            if (Id > 0 || Id != null)
            {
                pets = _petRepository.Pets().Where(p => p.BranchId == Id);
            }
            else
            {
                pets = _petRepository.Pets();
            }

            return View(pets);
        }

        [HttpGet]
        public ActionResult Create()
        {
            List<Breed> breeds = _breedRepository.Breeds();
            ViewBag.BreedsList = new SelectList(breeds, "Id", "BreedName");

            List<Branch> branches = _branchRepository.AllBranches();
            ViewBag.BranchList = new SelectList(branches, "Id", "Address");

            List<Owner> owners = _ownerRepository.AllOwners();
            ViewBag.OwnerList = new SelectList(owners, "Id", "OwnerName");
            return View();
        }

        [HttpPost]
        public ActionResult Create(Pet pet)
        {
            if(ModelState.IsValid)
            {
                _petRepository.NewPet(pet);
                return Redirect("~/Pet/Index");
            }
            return View();
        }

        [HttpGet]
        public ActionResult Edit(int Id)
        {
            Pet pet = _petRepository.AllPets().Where(p=>p.Id==Id).First();

            List<Breed> breeds = _breedRepository.Breeds();
            ViewBag.BreedsList = new SelectList(breeds, "Id", "BreedName", pet.BreedId);

            List<Branch> branches = _branchRepository.AllBranches();
            ViewBag.BranchList = new SelectList(branches, "Id", "Address", pet.BranchId);

            List<Owner> owners = _ownerRepository.AllOwners();

            owners.Add(new Owner { Id=0, OwnerName=""});
            ViewBag.OwnerList = new SelectList(owners, "Id", "OwnerName", pet.OwnerId==null?0:pet.OwnerId);

            return View(pet);
        }

        [HttpPost]
        public ActionResult Edit(Pet pet)
        {
            if(pet.OwnerId==0)
            {
                pet.OwnerId = null;
            }

            if(ModelState.IsValid)
            {
                _petRepository.EditPet(pet);
                return Redirect("~/Pet/Index");
            }
            return View(pet);
        }

        [HttpGet]
        public ActionResult Delete(int Id)
        {
            _petRepository.DeletePet(Id);
            return Redirect("~/Pet/Index");
        }
    }
}

ITEAProject/ITEAProject/Views/Branch/Create.cshtml
@model Branch
<form asp-controller="Branch" asp-action="Create" method="post">
    <span asp-validation-for="Address" class="text-danger"></span>
    <label asp-for="Address">Address</label><br>
    <input asp-for="Address" type="text" /><br>

    <span asp-validation-for="Phone" class="text-danger"></span>
    <label asp-for="Phone">Phone</label><br>
    <input asp-for="Phone" type="tel" /><br>

    <button type="submit">Create Branch</button>
</form>

ITEAProject/ITEAProject/Views/Branch/Index.cshtml
@model IEnumerable<Branch>

<a asp-action="Create" asp-controller="Branch">Create New</a>
<table class="table" style="text-align: center">
    <tr>
        <th>Id</th>
        <th>Address</th>
        <th>Phone</th>
    </tr>
    @foreach (var branch in Model)
    {
<tr>
    <td>@branch.Id</td>
    <td>@branch.Address</td>
    <td>@branch.Phone</td>
    <td><a asp-action="Update" asp-controller="Branch" asp-route-id="@branch.Id">Edit</a></td>
    <td><a asp-action="Delete" asp-controller="Branch" asp-route-id="@branch.Id">Delete</a></td>
    <td><a asp-action="Index" asp-controller="Pet" asp-route-id="@branch.Id">Watch pets</a></td>
</tr>
    }
</table>

ITEAProject/ITEAProject/Views/Branch/Update.cshtml
@model Branch
<form asp-controller="Branch" asp-action="Update" asp-route-id="@Model.Id"  method="post">

    <span asp-validation-for="Address" class="text-danger"></span>
    <label asp-for="Address">Address</label><br>
    <input asp-for="Address" type="text" /><br>

    <span asp-validation-for="Phone" class="text-danger"></span>
    <label asp-for="Phone">Phone</label><br>
    <input asp-for="Phone" type="text" /><br>

    <button type="submit">Save Changes</button>
</form>