ITEAProject/ITEAProject/Controllers/BreedController.cs
using ITEAProject.Models;
using ITEAProject.Models.ModelRepositories;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ITEAProject.Controllers
{
    public class BreedController : Controller
    {
        private readonly IBreedRepository _breedRepository;

        public BreedController(IBreedRepository breedRepository)
        {
            _breedRepository = breedRepository;
        }
        public ActionResult Index()
        {
            List<Breed> breeds = _breedRepository.Breeds();
            return View(breeds);
        }

        [HttpGet]
        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Create(Breed breed)
        {
            _breedRepository.Create(breed);
            return Redirect("~/Breed/Index");
        }

        [HttpGet]
        public ActionResult Update(int Id)
        {
            Breed breed = _breedRepository.Breeds().Where(b => b.Id == Id).First();
            return View(breed);
        }

        [HttpPost]
        public ActionResult Update(Breed breed)
        {
            if (ModelState.IsValid)
            {
                _breedRepository.Update(breed);
                return Redirect("~/Breed/Index");
            }
            return View(breed);
        }

        [HttpGet]
        public ActionResult Delete(int Id)
        {
            _breedRepository.Delete(Id);
            return Redirect("~/Breed/Index");
        }
    }
}

ITEAProject/ITEAProject/Controllers/ImageController.cs
using ITEAProject.Services;
using ITEAProject.Services.Repositories;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ITEAProject.Controllers
{
    public class ImageController:Controller
    {
        private readonly IRestApiClient _client;
        private readonly IFileService _fileService;

        public ImageController(IRestApiClient client, IFileService fileService)
        {
            _client = client;
            _fileService = fileService;
        }

        public IActionResult Get(string fileName)
        {
            byte[] imageBytes;

            imageBytes = _fileService.GetFileFromCache();
            if (imageBytes == null)
            {
                imageBytes = _client.GetFile();
                _fileService.SetToCache(imageBytes);
            }


            return new FileContentResult(imageBytes, "image/jpeg");
        }

    }
}

ITEAProject/ITEAProject/Controllers/OwnerController.cs
using ITEAProject.Models;
using ITEAProject.Models.ModelRepositories;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ITEAProject.Controllers
{
    public class OwnerController : Controller
    {
        private IOwnerRepository _ownerRepository;

        public OwnerController(IOwnerRepository ownerRepository)
        {
            _ownerRepository = ownerRepository;
        }
        public IActionResult Index()
        {
            List<Owner> owners = _ownerRepository.AllOwners();
            return View(owners);
        }

        [HttpGet]
        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Create(Owner owner)
        {
            if (ModelState.IsValid)
            {
                _ownerRepository.AddOwner(owner);
                return Redirect("~/Owner/Index");
            }
            return View();
        }

        [HttpGet]
        public IActionResult Update(int Id)
        {
            Owner owner = _ownerRepository.AllOwners().Where(br => br.Id == Id).First();
            return View(owner);
        }

        [HttpPost]
        public ActionResult Update(Owner owner)
        {
            if(ModelState.IsValid)
            {
                _ownerRepository.UpdateOwner(owner);
                return Redirect("~/Owner/Index");
            }

            return View(owner);
        }

        [HttpGet]
        public ActionResult Delete(int Id)
        {
            _ownerRepository.DeleteOwner(Id);
            return Redirect("~/Owner/Index");
        }
    }
}

ITEAProject/ITEAProject/Controllers/PetController.cs
using ITEAProject.Models;
using ITEAProject.Models.ModelRepositories;
using ITEAProject.ViewModels;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ITEAProject.Controllers
{
    public class PetController : Controller
    {
        private IPetRepository _petRepository;
        private IBranchRepository _branchRepository;
        private IBreedRepository _breedRepository;
        private IOwnerRepository _ownerRepository;

        public PetController(IPetRepository petRepository, IBreedRepository breedRepository, 
                             IBranchRepository branchRepository, IOwnerRepository ownerRepository)
        {
            _petRepository = petRepository;
            _breedRepository = breedRepository;
            _branchRepository = branchRepository;
            _ownerRepository = ownerRepository;
        }
        public IActionResult Index(int? Id)
        {
            IEnumerable<PetIndexViewModel> pets;
            if (Id > 0 || Id != null)
            {
                pets = _petRepository.Pets().Where(p => p.BranchId == Id);
            }
            else
            {
                pets = _petRepository.Pets();
            }

            return View(pets);
        }

        [HttpGet]
        public ActionResult Create()
        {
            List<Breed> breeds = _breedRepository.Breeds();
            ViewBag.BreedsList = new SelectList(breeds, "Id", "BreedName");

            List<Branch> branches = _branchRepository.AllBranches();
            ViewBag.BranchList = new SelectList(branches, "Id", "Address");

            List<Owner> owners = _ownerRepository.AllOwners();
            ViewBag.OwnerList = new SelectList(owners, "Id", "OwnerName");
            return View();
        }

        [HttpPost]
        public ActionResult Create(Pet pet)
        {
            if(ModelState.IsValid)
            {
                _petRepository.NewPet(pet);
                return Redirect("~/Pet/Index");
            }
            return View();
        }

        [HttpGet]
        public ActionResult Edit(int Id)
        {
            Pet pet = _petRepository.AllPets().Where(p=>p.Id==Id).First();

            List<Breed> breeds = _breedRepository.Breeds();
            ViewBag.BreedsList = new SelectList(breeds, "Id", "BreedName", pet.BreedId);

            List<Branch> branches = _branchRepository.AllBranches();
            ViewBag.BranchList = new SelectList(branches, "Id", "Address", pet.BranchId);

            List<Owner> owners = _ownerRepository.AllOwners();

            owners.Add(new Owner { Id=0, OwnerName=""});
            ViewBag.OwnerList = new SelectList(owners, "Id", "OwnerName", pet.OwnerId==null?0:pet.OwnerId);

            return View(pet);
        }

        [HttpPost]
        public ActionResult Edit(Pet pet)
        {
            if(pet.OwnerId==0)
            {
                pet.OwnerId = null;
            }

            if(ModelState.IsValid)
            {
                _petRepository.EditPet(pet);
                return Redirect("~/Pet/Index");
            }
            return View(pet);
        }

        [HttpGet]
        public ActionResult Delete(int Id)
        {
            _petRepository.DeletePet(Id);
            return Redirect("~/Pet/Index");
        }
    }
}

ITEAProject/ITEAProject/Views/Shared/_Layout.cshtml
@inject SignInManager<IdentityUser> _signInManager
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ITEAProject</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">ITEAProject</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Image" asp-action="Get">PictureCache</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Branch" asp-action="Index">Branches</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Breed" asp-action="Index">Breeds</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Pet" asp-action="Index" asp-route-id="@null">Pets</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Owner" asp-action="Index" asp-route-id="@null">Owners</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Stream" asp-action="Index">JokeSocket</a>
                        </li>
                    </ul>
                    <ul class="nav-bar">
                        @if (_signInManager.IsSignedIn(User))
                        {
                            <li class="nav-item">
                                <label>@User.Identity.Name</label>
                            </li>
                            <li class="nav-item">
                                <form asp-controller="Account" asp-action="Logout" method="post">
                                    <button type="submit">Logout</button>
                                </form>

                            </li>
                        }
                        else
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="Login">Login</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="Register">Register</a>
                            </li>
                        }
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - ITEAProject - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>